name: pulsar 
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - freetype=2.10.4=ha233b18_0
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.2.0=py37h04f5b5a_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h79c402e_3
  - matplotlib-base=3.3.2=py37h181983e_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy-base=1.19.2=py37hcfb5961_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=haf1e3a3_0
  - pillow=8.0.0=py37h1a82f1a_0
  - pip=20.0.2=py37_3
  - pyparsing=2.4.7=py_0
  - python=3.7.7=hf48f09d_4
  - python-dateutil=2.8.1=py_0
  - readline=8.0=h1de35cc_0
  - setuptools=46.4.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h5c1f38d_1
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h1de35cc_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  
